### ISSUE TITLE
npm run dev 执行的时候出错

### ISSUE THREAD

**Issue by Xiezhibin** [ntfstool/ntfstool#74]
npm run dev 执行的时候出错

Error: The module '/Users/danieltse/code/ntfstool/node_modules/usb-detection/build/Release/detection.node'
  was compiled against a different Node.js version using
  NODE_MODULE_VERSION 83. This version of Node.js requires
  NODE_MODULE_VERSION 76. Please try re-compiling or re-installing
  the module (for instance, using `npm rebuild` or `npm install`).
      at process.func [as dlopen] (electron/js2c/asar.js:140:31)
      at Object.Module._extensions..node (internal/modules/cjs/loader.js:1016:18)
      at Object.func [as .node] (electron/js2c/asar.js:140:31)
      at Module.load (internal/modules/cjs/loader.js:816:32)
      at Module._load (internal/modules/cjs/loader.js:728:14)
      at Function.Module._load (electron/js2c/asar.js:748:26)
      at Module.require (internal/modules/cjs/loader.js:853:19)
      at require (internal/modules/cjs/helpers.js:74:18)
      at bindings (/Users/danieltse/code/ntfstool/node_modules/bindings/bindings.js:112:48)
      at Object.<anonymous> (/Users/danieltse/code/ntfstool/node_modules/usb-detection/index.js:13:37)

┗ ----------------------------

**Comment by ntfstool** [comment]
The new version 3.5+ already supports Apple M1/M2/M3 and other chips.

Sorry for taking so long to update, because before that there was no good way to solve the compatibility problem of the new version of the system.

Fortunately, we have now been authorized by Apple to support the new version of the system kernel, so that we can fully support all macos systems through kernel drivers. Please experience it again, and if you have any questions, please update and communicate.
